name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build-app:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        if: needs.bootstrap.outputs.build-app == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1

      - name: Run install
        run: yarn workspaces focus app

      - run: |
          echo '{
            "github": {
              "silent": true
            },
            "framework": "nextjs",
            "installCommand": "(:)",
            "buildCommand": "(:)",
            "outputDirectory": "app/.next"
          }' > ./vercel.json
        if: needs.bootstrap.outputs.build-app == 'true'

      - run: yarn dlx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} --local-config=./vercel.json

      - run: cp ./.vercel/.env.preview.local ./app/.env

      - name: Build
        run: yarn workspace app run build
        timeout-minutes: 3

      - run: yarn dlx vercel build --local-config=./vercel.json

      - run: yarn dlx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --local-config=./vercel.json